---
name: Bump version & create Release

on:
    push:
        branches:
            - 'main'

jobs:
    create-release:
        if: "!startsWith(github.event.head_commit.message, 'bump:')"
        runs-on: ubuntu-latest
        name: 'Bump version and create release'
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: '${{ secrets.GITHUB_TOKEN }}'

            - name: Create bump and changelog
              uses: commitizen-tools/commitizen-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  changelog_increment_filename: body.md

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  body_path: 'body.md'
                  tag_name: ${{ env.REVISION }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
